service: url-shortener-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - http: GET fun
  crearEnlace:
    handler: enlaces/crear/crear.enlaces.handler
    events:
      - http: GET enlaces/crear

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: testTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
