service: url-shortener-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !GetAtt EnlaceTable.Arn

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: fun
          cors: true
          method: get
  crearEnlace:
    handler: enlaces/crear/crear.handler
    events:
      - http:
          path: enlaces/crear
          cors: true
          method: get
  listarEnlaces:
    handler: enlaces/listar/listar.handler
    events:
      - http:
          path: enlaces/listar
          method: get
          cors: true
  enlace:
    handler: enlaces/enlace/enlace.handler
    events:
      - http:
          path: enlaces/{id}
          cors: true
          method: get
  actualizarEnlace:
    handler: enlaces/actualizar/actualizar.handler
    events:
      - http:
          path: enlaces/actualizar/{id}
          cors: true
          method: get
  eliminarEnlace:
    handler: enlaces/eliminar/eliminar.handler
    events:
      - http:
          path: enlaces/eliminar/{id}
          cors: true
          method: get
  resolverEnlace:
    handler: enlaces/resolver/resolver.handler
    events:
      - http:
          path: enlaces/resolver/{enlace_corto}
          cors: true
          method: get
  expiracionEnlace:
    handler: enlaces/expiracion/expiracion.handler
    events:
      - http:
          path: enlaces/expiracion/{id}
          cors: true
          method: get

resources:
  Resources:
    EnlaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: enlacesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
