service: url-shortener-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !GetAtt EnlaceTable.Arn

functions:
  function1:
    handler: index.handler
    events:
      - http: GET fun
  crearEnlace:
    handler: enlaces/crear/crear.handler
    events:
      - http: GET enlaces/crear
  listarEnlaces:
    handler: enlaces/listar/listar.handler
    events:
      - http: GET enlaces/listar
  enlace:
    handler: enlaces/enlace/enlace.handler
    events:
      - http: GET enlaces/{id}
resources:
  Resources:
    EnlaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: enlacesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
